name: python cpstl release

on:
  release:
    types: [created]
    tags:
      - python-v*

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python env
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Publish
        run: |
          cd python
          python -m pip install --upgrade pip
          pip install poetry
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
          poetry config virtualenvs.create false
          poetry publish --build